services:
  portfolio-api:
    image: ghcr.io/samuelpanzera/portfolio-api:latest
    container_name: portfolio-api
    restart: always
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      - PORT=3000
